# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import media_pb2 as media__pb2


class MediaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.filter = channel.stream_stream(
        '/MediaService/filter',
        request_serializer=media__pb2.audio.SerializeToString,
        response_deserializer=media__pb2.inferredResult.FromString,
        )


class MediaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def filter(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'filter': grpc.stream_stream_rpc_method_handler(
          servicer.filter,
          request_deserializer=media__pb2.audio.FromString,
          response_serializer=media__pb2.inferredResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MediaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
